### ISSUE TITLE
Crashed when someone on IRC posted a dropbox link

### ISSUE THREAD

**Issue by voneiden** [kurkku/slack-irc-bot#2]
The bot (probably) crashed when someone on IRC typed a dropbox image link. Nobody wrote anything on slack end, so I guess this was triggered by the bot's own slack message?

```
TypeError: Cannot read property '0' of undefined
    at Bot.sendToIRC (/usr/local/lib/node_modules/slack-irc-bot/libs/bot.js:91:28)
```

**Comment by voneiden** [comment]
Example url for replicating: https://www.dropbox.com/s/I.jpg?dl=0

**Comment by kurkku** [comment]
IRC bot was trying to use undefined element in a Slack bot message hence the crash. Will fix shortly.
